spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/barbearia
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=YmFyYmVhcmlhLXNlY3JldC1rZXktbXVpdG8tc2VndXJhLTIwMjQ=
jwt.expiration=86400000


server.port=8080